const products = [
  {
    name: "مزيل عرق كريم أفون للنساء بدون عطر – 50غ",
    brand: "Avon",
    line: "AVON DESODORANTE",
    category: "العناية الشخصية",
    description: "تركيبة لطيفة وخالية من العطور، تحمي من التعرق وتناسب البشرة الحساسة دون التسبب في التهيج.",
    usage: "يُستخدم يوميًا تحت الإبطين على بشرة نظيفة وجافة.",
    explanation: "يوفر حماية فعالة ويمنح شعوراً بالنظافة دون تغطية برائحة.",
    image: "images/135727.png",
    name_pt: "AVON DESOD CREME SEM PERFUM FEM 50G",
    price: 4.1,
  },
  {
    name: "مزيل عرق كريم أكوافايب برائحة الأطفال – 50غ",
    brand: "Avon",
    line: "AVON DESODORANTE",
    category: "العناية الشخصية",
    description: "مزيل عرق لطيف برائحة بودرة الأطفال، غني بمرطبات للبشرة، يوفر حماية تدوم 48 ساعة.",
    usage: "يوضع على بشرة نظيفة وجافة تحت الإبط.",
    explanation: "مناسب للبشرة الحساسة، لا يسبب التهيج ويمتص بسرعة دون أن يترك بقايا.",
    image: "images/135725.png",
    name_pt: "AQUAVIBE DESODORANTE CREME BABY SMEL 50G",
    price: 4.1,
  },
  {
    name: "مزيل عرق كريم أفون برائحة الأعشاب الحلوة – 50غ",
    brand: "Avon",
    line: "AVON DESODORANTE",
    category: "العناية الشخصية",
    description: "تركيبة غنية بخلاصة الأعشاب الحلوة، توفر حماية فعالة ضد التعرق وتترك رائحة طبيعية ومنعشة.",
    usage: "يُستخدم يوميًا على بشرة نظيفة وجافة.",
    explanation: "يمنح راحة وثقة طوال اليوم مع ترطيب خفيف وعطر منعش يدوم.",
    image: "images/135726.png",
    name_pt: "AVON DESODE CREME ERVA DOCE 50G",
    price: 4.1,
  },
  {
    name: "مزيل عرق كريم فار أواي سبلندوريا – أكسل",
    brand: "Avon",
    line: "AVON DESODORANTE",
    category: "العناية الشخصية",
    description: "مزيل عرق برائحة فاخرة من مجموعة Far Away، يمنح حماية تدوم 48 ساعة وعطرًا يدوم طويلاً.",
    usage: "يُستخدم يوميًا على بشرة نظيفة وجافة تحت الإبط.",
    explanation: "يجمع بين الأناقة والحماية، يمنح إحساسًا بالانتعاش مع لمسة عطرية ساحرة.",
    image: "images/177792.png",
    name_pt: "FAR AWAY SPLENDORIA DESOD CREME AXL",
    price: 4.1,
  },
  {
    name: "مزيل عرق كريم فار أواي أورجينال – أكسل",
    brand: "Avon",
    line: "AVON DESODORANTE",
    category: "العناية الشخصية",
    description: "نفس العطر الكلاسيكي الشهير من Far Away بتركيبة مزيل عرق ناعمة وفعالة.",
    usage: "يُستخدم يوميًا.",
    explanation: "مثالي للنساء الباحثات عن حماية يومية برائحة أنثوية تقليدية من أفون.",
    image: "images/177793.png",
    name_pt: "FAR AWAY ORIGINAL DESOD CREME AXL",
    price: 4.1,
  },
  {
    name: "مزيل عرق كريم فار أواي غلامور – أكسل",
    brand: "Avon",
    line: "AVON DESODORANTE",
    category: "العناية الشخصية",
    description: 'تركيبة منعشة برائحة "Glamour" الجريئة والمميزة، مع حماية من الرطوبة والتعرق.',
    usage: "يُوضع على الإبطين النظيفين.",
    explanation: "حماية تدوم طويلاً بعطر أنيق يضيف لمسة من التألق والثقة.",
    image: "images/179546.png",
    name_pt: "FAR AWAY GLAMOUR DESOD CREME AXL",
    price: 4.718,
  },
  {
    name: "كريم أفون كير لليدين بالسيليكون – 75غ",
    brand: "Avon",
    line: "AVON CARE",
    category: "عناية باليدين",
    description: "يحتوي على السيليكون الذي يشكل طبقة واقية على اليدين، يحمي من الجفاف ويمنح ترطيبًا عميقًا.",
    usage: "يُستخدم على اليدين عدة مرات يومياً حسب الحاجة.",
    explanation: "يرطب ويحمي اليدين من العوامل الخارجية مع ملمس غير دهني.",
    image: "images/161063.png",
    name_pt: "AVON CARE CR DES MAO SILICONE 75G",
    price: 6.45,
  },
  {
    name: "كريم أفون كير لليدين بالسيليكون والمكاديميا – 75غ",
    brand: "Avon",
    line: "AVON CARE",
    category: "عناية باليدين",
    description: "تركيبة تجمع بين السيليكون المغلف والزيت الطبيعي من المكاديميا لترطيب يدوم طويلًا.",
    usage: "يُستخدم على اليدين النظيفة ويدلك حتى الامتصاص.",
    explanation: "يغذي البشرة بعمق ويحسن من مرونتها مع حماية فعالة من الجفاف.",
    image: "images/161079.png",
    name_pt: "AVON CARE CR DES MAO SILIC MACADAMIA 75G",
    price: 6.45,
  },
  {
    name: "كريم أفون فُت وركس لترطيب القدمين المكثف – 80غ",
    brand: "Avon",
    line: "AVON CARE",
    category: "عناية بالقدمين",
    description: "تركيبة غنية بزبدة الشيا ومضادات البكتيريا، يرطب الكعبين المتشققين ويهدئ التعب.",
    usage: "يُوضع على القدمين النظيفة مع تدليك حتى الامتصاص.",
    explanation: "يمنح راحة فورية للقدمين ويُستخدم يومياً للعناية المستمرة.",
    image: "images/174931.png",
    name_pt: "FOOTWORKS HID DES PES INTENSIVA 80G",
    price: 10.55,
  },
  {
    name: "كريم الوجه الليلي أفون كير – ليلة سعيدة – 100غ",
    brand: "Avon",
    line: "AVON CARE",
    category: "عناية بالبشرة",
    description: "يحتوي على البانثينول ومغذيات الليل التي تعمل أثناء النوم لتغذية البشرة وتجديدها.",
    usage: "يوضع ليلاً بعد تنظيف البشرة.",
    explanation: "يعزز تجدد البشرة أثناء النوم ويمنحها مظهراً منتعشاً عند الاستيقاظ.",
    image: "images/136026.png",
    name_pt: "AVON CARE CREME FAC BOA NOITE 100G",
    price: 10.79,
  },
  {
    name: "كريم الوجه النهاري أفون كير بالفيتامينات المتعددة – 100غ",
    brand: "Avon",
    line: "AVON CARE",
    category: "عناية بالبشرة",
    description:
      "يحتوي على مزيج من الفيتامينات A، C، و E، يمنح البشرة إشراقًا وترطيبًا مع حماية خفيفة من العوامل البيئية.",
    usage: "يوضع صباحًا على الوجه والرقبة.",
    explanation: "مثالي للبشرة الباهتة، يعزز الحيوية والترطيب مع الاستخدام اليومي.",
    image: "images/152724.png",
    name_pt: "AVON CARE MULTIVITAMIN CREME DIA 100G",
    price: 10.79,
  },
  {
    name: "كريم الوجه النهاري من أفون كير لمقاومة التجاعيد – 100غ",
    brand: "Avon",
    line: "AVON CARE",
    category: "عناية بالبشرة",
    description: "غني بالكولاجين وفيتامين E، يساعد في تقليل مظهر الخطوط الدقيقة ويحافظ على ترطيب البشرة طوال اليوم.",
    usage: "يوضع صباحًا على وجه نظيف وجاف.",
    explanation: "يحارب علامات التقدم في السن ويوفر ترطيباً مستمراً.",
    image: "images/136024.png",
    name_pt: "AVON CARE CREME FAC ANTISSINAIS DIA 100G",
    price: 10.79,
  },
  {
    name: "مجموعة رول أون تفتيح من تودوديا",
    brand: "Natura",
    line: "TODODIA",
    category: "العناية الشخصية",
    description:
      "يحتوي على مكونات مبيضة مثل النياسيناميد، يقلل من البقع الداكنة تحت الإبط ويمنح رائحة منعشة طوال اليوم.",
    usage: "يُستخدم يوميًا على بشرة نظيفة وجافة تحت الإبطين.",
    explanation: "يفتّح البشرة بلطف ويحمي من التعرق بتركيبة فعالة وغير مهيجة.",
    image: "images/130305.png",
    name_pt: "TODODIA CJ ROLL ON ACLARAR 3 UN",
    price: 15.95,
  },
  {
    name: "كريم مزيل عرق تودوديا برائحة زهرة الليس – 80غ",
    brand: "Natura",
    line: "TODODIA",
    category: "العناية الشخصية",
    description:
      "مزيل عرق كريم بخلاصة زهرة الليس، تركيبة خفيفة ولطيفة على البشرة، تمنح حماية تدوم 48 ساعة دون أن تترك بقعًا أو علامات.",
    usage: "يُستخدم يوميًا على بشرة نظيفة وجافة تحت الإبط.",
    explanation: "يحافظ على الإنتعاش طوال اليوم، ويوفر عناية ناعمة ورائحة زهرية ناعمة وثابتة.",
    image: "images/96518.png",
    name_pt: "TODODIA DES CREME FLOR DE LIS INVIS 80G",
    price: 16.6,
  },
  {
    name: "كريم مزيل عرق تودوديا بالمكاديميا – 80غ",
    brand: "Natura",
    line: "TODODIA",
    category: "العناية الشخصية",
    description:
      "تركيبة لطيفة بخلاصة زيت المكاديميا، تحمي من التعرق لمدة تصل إلى 48 ساعة، دون أن تترك بقعًا على الملابس.",
    usage: "يُستخدم يوميًا على بشرة نظيفة وجافة تحت الإبط.",
    explanation: "يرطب البشرة ويحافظ على نعومتها، مع حماية فعالة ورائحة طبيعية خفيفة تدوم طوال اليوم.",
    image: "images/1925.png",
    name_pt: "TODODIA¿DES CREME MACADAMIA INVIS 80G",
    price: 16.6,
  },
  {
    name: "كريم اليدين تودوديا بالمانغا الوردية وجوز الهند – 50مل",
    brand: "Natura",
    line: "TODODIA",
    category: "عناية باليدين",
    description:
      "يحتوي على خلاصة المانغا الوردية وزيت جوز الهند، يرطب اليدين ويتركها ناعمة ومعطرة برائحة استوائية منعشة.",
    usage: "يُستخدم عدة مرات يوميًا حسب الحاجة.",
    explanation: "مثالي للترطيب الفوري، لا يترك أثراً دهنياً ويمتص بسرعة.",
    image: "images/95937.png",
    name_pt: "TODODIA HID MAOS MANGA ROSA COCO 50ML",
    price: 17.43,
  },
  {
    name: "كريم اليدين تودوديا بالكرز والفانيليا – 50مل",
    brand: "Natura",
    line: "TODODIA",
    category: "عناية باليدين",
    description: "يحتوي على زيت الكرز وخلاصة الفانيليا، يرطب اليدين بعمق ويمنحهما عطراً حلواً ومنعشاً.",
    usage: "يُستخدم حسب الحاجة على اليدين طوال اليوم.",
    explanation: "كريم خفيف وسريع الامتصاص، يمنح ترطيباً فعالاً وعطراً مميزاً يدوم طويلاً.",
    image: "images/959371.png",
    name_pt: "tododia hidcereja eavela maos50ml",
    price: 17.43,
  },
  {
    name: "زيت الأرغان وجوز الهند للعلاج من أدفانسد تكنيك – 30مل",
    brand: "Avon",
    line: "Avon OLEO",
    category: "عناية بالشعر",
    description: "نفس فوائد الإصدار 90مل بتركيبة مكثفة وسهلة الحمل، يعيد الترطيب والنعومة للشعر التالف.",
    usage: "يُستخدم بعد الغسيل أو على الشعر الجاف حسب الحاجة.",
    explanation: "يُرطب بعمق ويغذي الشعر من الجذور للأطراف بفضل الزيوت الطبيعية.",
    image: "images/135141.png",
    name_pt: "ADV TECH OLEO ARGAN TRATAMENTO COCO 30ML",
    price: 17.79,
  },
  {
    name: "سيروم الأرغان والكاميليا من أدفانسد تكنيك – 30مل",
    brand: "Avon",
    line: "Avon OLEO",
    category: "عناية بالشعر",
    description: "يحتوي على زيت الأرغان وزهرة الكاميليا، يساعد على ترطيب الشعر بعمق وتنعيمه ومنع تقصف الأطراف.",
    usage: "يُوضع على شعر رطب أو جاف بعد الاستحمام.",
    explanation: "يمنح مظهرًا صحيًا وناعمًا للشعر مع تقوية الأطراف ومنع تكسرها.",
    image: "images/135140.png",
    name_pt: "ADV TECH OLEO ARGAN SERUM CAMELIA 30ML",
    price: 17.79,
  },
  {
    name: "كريم تمشيط مغذي من تودوديا",
    brand: "Natura",
    line: "TODODIA",
    category: "عناية بالشعر",
    description: "غني بزيت المكاديميا وخلاصة الشوفان، يغذي الشعر ويمنع تشابكه ويمنحه نعومة فورية.",
    usage: "يُستخدم على شعر نظيف ومبلل دون شطف.",
    explanation: "يساعد في تقوية الشعر وجعله أكثر سهولة في التصفيف.",
    image: "images/156237.png",
    name_pt: "TODODIA CRM COND PENTEAR NUTRITIVO 180ML",
    price: 19.7,
  },
  {
    name: "ماسك مغذي للشعر من تودوديا – 250مل",
    brand: "Natura",
    line: "TODODIA",
    category: "عناية بالشعر",
    description: "تركيبة غنية بزيوت نباتية ومكونات مغذية، تعزز ترميم الشعر الجاف والتالف وتمنحه ترطيبًا عميقًا.",
    usage: "يُوضع على الشعر بعد الغسل ويُترك 3–5 دقائق ثم يُشطف جيدًا.",
    explanation: "يعيد حيوية الشعر ويجعله أكثر نعومة ولمعانًا.",
    image: "images/154872.png",
    name_pt: "TODODIA COND MASCARA NUTRICAO 250ML",
    price: 20.0,
  },
  {
    name: "جل بلسم تودوديا لتجاعيد الشعر والكيرلي – 250غ",
    brand: "Natura",
    line: "TODODIA",
    category: "عناية بالشعر",
    description:
      "تركيبة مخصصة للشعر المجعد والكيرلي، تحتوي على زيوت طبيعية ومرطبات لتعريف التموجات ومنحها مرونة وثبات.",
    usage: "يُستخدم على شعر رطب بعد غسله، دون شطف.",
    explanation: "يُظهر جمال التموجات الطبيعية للشعر ويقلل من تطايره.",
    image: "images/173590.png",
    name_pt: "TODODIA COND GEL CACHOS E CRESPOS 250G",
    price: 20.0,
  },
  {
    name: "كريم تفتيح الوجه من فايسز مع واقي شمس",
    brand: "Avon",
    line: "FACES",
    category: "عناية بالبشرة",
    description: "غني بفيتامين C ونياسيناميد، مع واقٍ شمسي SPF15، يفتح البشرة تدريجياً ويمنع التصبغات الناتجة عن الشمس.",
    usage: "يوضع صباحاً على الوجه بعد التنظيف.",
    explanation: "يساعد في توحيد لون البشرة وتقليل البقع الداكنة بفضل مكوناته المبيضة.",
    image: "images/91821.png",
    name_pt: "FACES CLAREADOR FACIAL PELE M O FPS15",
    price: 25.13,
  },
  {
    name: "كريم تفتيح الوجه فايسز للبشرة العادية والجافة – SPF15",
    brand: "Avon",
    line: "FACES",
    category: "عناية بالبشرة",
    description: "يحتوي على فيتامين C ونياسيناميد، يوحد لون البشرة ويحميها من أشعة الشمس بفضل SPF15.",
    usage: "يوضع صباحًا على بشرة نظيفة قبل الخروج.",
    explanation: "يساعد في تقليل التصبغات ويمنح إشراقة للبشرة مع حماية يومية.",
    image: "images/91820.png",
    name_pt: "FACES CLAREADOR FACIAL PELE N S FPS15",
    price: 25.13,
  },
  {
    name: "شامبو التغذية تودوديا",
    brand: "Natura",
    line: "TODODIA",
    category: "عناية بالشعر",
    description: "يحتوي على زيت اللوز الحلو، وخلاصة النباتات المغذية، ينظف ويرطب الشعر بلطف مع تحسين مرونته.",
    usage: "يُستخدم على شعر مبلل، يُدلك بلطف ثم يُشطف جيدًا.",
    explanation: "يمنح الشعر مظهرًا صحيًا ولمعانًا طبيعيًا مع الاستخدام المنتظم.",
    image: "images/154869.png",
    name_pt: "TODODIA SH NUTRICAO 300ML",
    price: 27.12,
  },
  {
    name: "شامبو ترطيب تودوديا",
    brand: "Natura",
    line: "TODODIA",
    category: "عناية بالشعر",
    description: "يحتوي على خلاصة اللوز الحلو، وزبدة الشيا، ينظف الشعر بلطف ويرطبه من الجذور حتى الأطراف.",
    usage: "يُستخدم على شعر مبلل، يُدلك حتى تتكون رغوة ثم يُشطف جيدًا.",
    explanation: "يمنح الشعر نعومة ولمعانًا طبيعيًا مع ترطيب طويل الأمد.",
    image: "images/154866.png",
    name_pt: "TODODIA SH HIDRATACAO 300ML",
    price: 27.12,
  },
  {
    name: "كريم ترطيب اليدين إكوس بزيت الكستناء – 40غ",
    brand: "Natura",
    line: "EKOS",
    category: "عناية باليدين",
    description: "غني بزيت الكستناء الأمازوني، يرطب اليدين بعمق ويعزز من حاجز الحماية الطبيعي للبشرة.",
    usage: "يُستخدم عدة مرات يوميًا على اليدين حسب الحاجة.",
    explanation: "يمنح اليدين نعومة فائقة ويحميهما من الجفاف خاصة في الأجواء الباردة.",
    image: "images/69821.png",
    name_pt: "ekos hidpolpa maoscastanha40g nf",
    price: 27.23,
  },
  {
    name: "كريم ترطيب اليدين إكوس أنديوروبا – 40غ",
    brand: "Natura",
    line: "EKOS",
    category: "عناية باليدين",
    description:
      "يحتوي على زيت الأنديوروبا المستخرج من غابات الأمازون، يعيد توازن البشرة، يرطب اليدين بعمق ويمنح حماية طبيعية.",
    usage: "يُستخدم عدة مرات يومياً حسب الحاجة.",
    explanation: "مثالي للبشرة الحساسة أو المتعبة، يهدئ ويرمم الجلد الجاف ويمنحه نعومة فورية دون أن يترك ملمساً دهنياً.",
    image: "images/147195.png",
    name_pt: "Polpa Hidratante para as Mãos Ekos Andiroba 40 g",
    price: 27.23,
  },
  {
    name: "كريم ترطيب اليدين إكوس بيتانغا سوداء",
    brand: "Natura",
    line: "EKOS",
    category: "عناية باليدين",
    description:
      "غني بزيت فاكهة البيتّانغا السوداء ومضادات الأكسدة، يرطب اليدين بعمق ويتركهما ناعمتين مع عطر فاكهي جذاب.",
    usage: "يُستخدم عدة مرات يومياً حسب الحاجة.",
    explanation: "يرطب البشرة الجافة، يمنع التشققات، ويمنح اليدين إحساساً بالراحة والانتعاش مع لمسة عطرية تدوم.",
    image: "images/122945.png",
    name_pt: "Polpa Hidratante para Mãos Ekos Pitanga Preta",
    price: 27.23,
  },
  {
    name: "غسول نسائي لطيف من تودوديا",
    brand: "Natura",
    line: "TODODIA",
    category: "العناية الشخصية",
    description:
      "تركيبة خفيفة ومتوازنة الأس الهيدروجيني، تحتوي على خلاصة القطن والبابونج لراحة لطيفة ومناسبة للاستخدام اليومي.",
    usage: "يُستخدم خارجيًا يوميًا أثناء الاستحمام، ثم يُشطف جيدًا.",
    explanation: "ينظف بلطف ويحافظ على التوازن الطبيعي للمنطقة الحساسة مع إحساس دائم بالانتعاش.",
    image: "images/83641.png",
    name_pt: "TODODIA SAB LIQ INTIMO SUAVE CONFORTO",
    price: 27.23,
  },
  {
    name: "زيت الأرغان وجوز الهند للعلاج من أدفانسد تكنيك – 90مل",
    brand: "Avon",
    line: "Avon OLEO",
    category: "عناية بالشعر",
    description:
      "تركيبة مغذية تحتوي على زيت الأرغان وزيت جوز الهند، ترطب الشعر الجاف والمتقصف وتعيد له الحيوية والنعومة.",
    usage: "يُوضع على أطراف الشعر الرطب أو الجاف دون شطف.",
    explanation: "مثالي للشعر الجاف والمجعد، يقلل من التكسر والتطاير ويمنح الشعر لمعانًا طبيعيًا.",
    image: "images/135144.png",
    name_pt: "ADV TECH OLEO ARGAN TRATAMENTO COCO 90ML",
    price: 33.74,
  },
  {
    name: "سيروم أرغان ثنائي الطبقة من أدفانسد تكنيك – 90مل",
    brand: "Avon",
    line: "Avon OLEO",
    category: "عناية بالشعر",
    description: "تركيبة ثنائية خفيفة بزيت الأرغان ومكونات مرطبة تساعد على فك تشابك الشعر وترطيبه دون إثقاله.",
    usage: "يُرج جيدًا قبل الاستخدام ويوضع على الشعر النظيف.",
    explanation: "يمنح الشعر ترطيبًا ولمعانًا مع تأثير خفيف وبدون مظهر زيتي.",
    image: "images/135145.png",
    name_pt: "ADV TECH OLEO ARGAN SERUM BIFASICO 90ML",
    price: 33.74,
  },
  {
    name: "سيروم الأرغان والكاميليا من أدفانسد تكنيك",
    brand: "Avon",
    line: "Avon OLEO",
    category: "عناية بالشعر",
    description: "تركيبة احترافية بزيت الأرغان وزهرة الكاميليا، يرطب ويغذي الشعر ويمنع التقصف والتطاير.",
    usage: "يُوضع على أطراف الشعر الجاف أو الرطب دون شطف.",
    explanation: "يحسن ملمس الشعر ويمنحه لمعانًا صحيًا دون إثقاله.",
    image: "images/135143.png",
    name_pt: "ADV TECH OLEO ARGAN SERUM CAMELIA 90ML",
    price: 33.74,
  },
  {
    name: "صابون سائل مقشر تودوديا برائحة الليمون والنعناع",
    brand: "Natura",
    line: "TODODIA",
    category: "العناية الشخصية",
    description: "يحتوي على حبيبات تقشير طبيعية، وخلاصة النعناع والليمون، ينظف ويجدد البشرة برائحة منعشة.",
    usage: "يُستخدم على بشرة مبللة، يُفرك بلطف ثم يُشطف جيداً.",
    explanation: "يزيل خلايا الجلد الميتة وينعش البشرة ويمنحها نعومة وانتعاشًا يدومان.",
    image: "images/113412.png",
    name_pt: "TODODIA SAB LIQUIDO ESFOL CAPIM 190G",
    price: 34.23,
  },
  {
    name: "شامبو ليمينا للتصبغات",
    brand: "Natura",
    line: "LUMINA",
    category: "عناية بالشعر",
    description: "يحتوي على أصباغ بنفسجية، خلاصة البابونج، وبروفيتامين B5، يزيل الاصفرار من الشعر الأشقر أو الرمادي.",
    usage: "يوضع على الشعر المبلل، يدلك بلطف ثم يشطف جيدًا.",
    explanation: "يعادل لون الشعر ويحافظ على إشراقه الطبيعي دون التسبب بجفاف.",
    image: "images/148158.png",
    name_pt: "LUMINA SH MATIZACAO 300ML",
    price: 39.12,
  },
  {
    name: "مقشر الجسم تودوديا بالمكاديميا – 200مل",
    brand: "Natura",
    line: "TODODIA",
    category: "عناية بالجسم",
    description: "يحتوي على حبيبات تقشير طبيعية وزيت المكاديميا، يزيل خلايا الجلد الميتة ويترك البشرة ناعمة.",
    usage: "يُستخدم على بشرة مبللة ويُدلك بلطف ثم يُشطف.",
    explanation: "يجدد البشرة ويمنحها مظهرًا مشرقًا وملمسًا ناعمًا.",
    image: "images/140759.png",
    name_pt: "TODODIA ESFOL MACADAMIA 200ML",
    price: 40.0,
  },
  {
    name: "جل الجسم المضيء من تودوديا برائحة الكاجو – 100غ",
    brand: "Natura",
    line: "TODODIA",
    category: "عناية بالجسم",
    description: "جل مرطب بتركيبة خفيفة ولامعة، غني بزيت الكاجو وفيتامين E، يمنح ترطيبًا ولمعانًا لطيفًا للبشرة.",
    usage: "يُوضع على بشرة نظيفة ويدلك بلطف حتى الامتصاص.",
    explanation: "يترك البشرة ناعمة ولمّاعة برائحة فاكهية استوائية.",
    image: "images/172410.png",
    name_pt: "tododia descorp gelilum caj100g",
    price: 40.0,
  },
  {
    name: "كريم تمشيط ليمينا للشعر المجعد",
    brand: "Natura",
    line: "LUMINA",
    category: "عناية بالشعر",
    description: "غني بزيت المكاديميا وزيت جوز الهند، يرطب ويفك التشابك ويعرّف تموجات الشعر المجعد دون أن يتركه دهنيًا.",
    usage: "يوضع على شعر رطب بعد الاستحمام دون شطف.",
    explanation: "يعزز مرونة الخصلات المجعدة ويتركها ناعمة ومعرّفة وطبيعية.",
    image: "images/148436.png",
    name_pt: "LUMINA COND CR PENTEAR CRESPOS 300ML",
    price: 43.92,
  },
  {
    name: "بخاخ ليمينا اللامع لتثبيت اللون",
    brand: "Natura",
    line: "LUMINA",
    category: "عناية بالشعر",
    description:
      "يحتوي على مضادات الأكسدة، زيت المكاديميا، وبروتينات نباتية، يمنح الشعر المصبوغ لمعانًا ويحافظ على لونه.",
    usage: "يُرش على الشعر النظيف الرطب أو الجاف دون شطف.",
    explanation: "يحمي الشعر المصبوغ من البهتان ويضيف له تألقًا طبيعيًا ولمسة نهائية حريرية.",
    image: "images/148449.png",
    name_pt: "LUMINA COND SPRAY BRI COR 150ML TERC",
    price: 45.225,
  },
  {
    name: "زيت ليمينا لتجعيدات الشعر",
    brand: "Natura",
    line: "LUMINA",
    category: "عناية بالشعر",
    description: "غني بزيت المكاديميا، وزيت جوز الهند، يساعد في ترطيب وتعريف تجاعيد الشعر.",
    usage: "يوضع على أطراف الشعر الرطب أو الجاف، مع التوزيع بأطراف الأصابع.",
    explanation: "يعزز مرونة التجاعيد ويحمي الشعر من الجفاف ويمنحه لمعانًا طبيعيًا.",
    image: "images/148165.png",
    name_pt: "LUMINA OLEO CACH CRE 100ML TERC",
    price: 51.225,
  },
  {
    name: "بخاخ ليمينا لتجعيدات الشعر – 150مل",
    brand: "Natura",
    line: "LUMINA",
    category: "عناية بالشعر",
    description: "يحتوي على مكونات مرطبة وزيوت نباتية تساعد على تنشيط التموجات وتعريف الشعر المجعد دون أن يترك بقايا.",
    usage: "يُرش على الشعر الرطب أو الجاف حسب الحاجة.",
    explanation: "يمنح تموجات طبيعية مرنة ولمعانًا ناعمًا دون إثقال الشعر.",
    image: "images/148419.png",
    name_pt: "lumina spryrea cachcre 150mlterc",
    price: 51.73,
  },
  {
    name: "بخاخ ليمينا لتأثير التصفيف والملمس – 150مل",
    brand: "Natura",
    line: "LUMINA",
    category: "عناية بالشعر",
    description: "تركيبة خفيفة لزيادة كثافة الشعر وإعطائه ملمسًا حيويًا ومظهرًا مشدودًا، غني بالبروتينات النباتية.",
    usage: "يُرش على الشعر الجاف ويُصفف حسب الرغبة.",
    explanation: "مناسب لتصفيف الشعر اليومي وزيادة حجمه وثباته دون تثقيله.",
    image: "images/148455.png",
    name_pt: "luminaspray text150ml terc",
    price: 51.73,
  },
  {
    name: "كريم الليل رينيو ألتيميت – 50غ",
    brand: "Avon",
    line: "RENEW",
    category: "عناية بالبشرة",
    description: "يحتوي على حمض الألفا هيدروكسي ومكونات مرطبة، يجدد البشرة أثناء النوم ويحسن ملمسها.",
    usage: "يوضع ليلاً على بشرة نظيفة قبل النوم.",
    explanation: "يعزز عملية تجدد الخلايا ويترك البشرة ناعمة ومشدودة عند الاستيقاظ.",
    image: "images/22222.png",
    name_pt: "RENEW ULTIMATE NOITE 50G",
    price: 52.26,
  },
  {
    name: "سيروم ليمينا لتجديد الشعر – 100مل",
    brand: "Natura",
    line: "LUMINA",
    category: "عناية بالشعر",
    description: "يحتوي على مزيج من الزيوت الثمينة والبروتينات النباتية، يعيد بناء الشعر التالف ويمنحه لمعانًا.",
    usage: "يُوضع على الشعر الرطب أو الجاف بعد غسله.",
    explanation: "يساعد في تقوية الشعر وتغذيته من الجذور حتى الأطراف.",
    image: "images/148429.png",
    name_pt: "LUMINA SERUM REESTRUTURANTE 100ML",
    price: 54.225,
  },
  {
    name: "كريم النهار رينيو ألتيميت – 50غ",
    brand: "Avon",
    line: "RENEW",
    category: "عناية بالبشرة",
    description: "يحتوي على واقي شمسي SPF25، يساعد في حماية البشرة من أشعة الشمس الضارة ويقلل من ظهور التجاعيد.",
    usage: "يوضع صباحًا على بشرة نظيفة قبل التعرض للشمس.",
    explanation: "يحافظ على شباب البشرة ويحميها من التلف الناتج عن الشمس.",
    image: "images/06212.png",
    name_pt: "RENEW ULTIMATE DIA FPS25 50G",
    price: 55.26,
  },
  {
    name: "كريم العين رينيو ألتيميت – 15غ",
    brand: "Avon",
    line: "RENEW",
    category: "عناية بالبشرة",
    description: "يحتوي على مكونات مضادة للشيخوخة، يساعد في تقليل ظهور الهالات السوداء والانتفاخات حول العينين.",
    usage: "يوضع بلطف حول منطقة العينين صباحًا ومساءً.",
    explanation: "يحسن مظهر منطقة العين ويمنحها إشراقًا وشبابًا.",
    image: "images/06213.png",
    name_pt: "RENEW ULTIMATE CREME AREA OLHOS 15G",
    price: 55.26,
  },
  {
    name: "مصل مركز لتجديد البشرة من رينيو – 30مل",
    brand: "Avon",
    line: "RENEW",
    category: "عناية بالبشرة",
    description: "تركيبة متطورة تحتوي على مكونات فعالة لتجديد البشرة وتحسين ملمسها ومظهرها.",
    usage: "يوضع على بشرة نظيفة قبل استخدام الكريم المرطب.",
    explanation: "يعزز من فعالية منتجات العناية بالبشرة الأخرى ويمنح البشرة مظهرًا أكثر شبابًا.",
    image: "images/06211.png",
    name_pt: "RENEW CLINICAL DERMO CONCENTRADO 30ML",
    price: 60.26,
  },
  {
    name: "مجموعة العناية بالبشرة رينيو ألتيميت",
    brand: "Avon",
    line: "RENEW",
    category: "عناية بالبشرة",
    description: "مجموعة متكاملة للعناية بالبشرة تحتوي على كريم النهار، كريم الليل، وكريم العين.",
    usage: "تُستخدم المجموعة يوميًا للحصول على أفضل النتائج.",
    explanation: "توفر المجموعة حماية وترطيب وتجديد للبشرة للحفاظ على شبابها.",
    image: "images/07374.png",
    name_pt: "RENEW ULTIMATE KIT ROTINA FACIAL",
    price: 165.78,
  },
]

export default products
